import { Theme } from './symbols';

export const mediumFonts: Theme = {
  name: 'medium',
  properties: {
    '--font-sizefive': '5px',
    '--font-sizesix': '6px',
    '--font-sizeseven': '7px',
    '--font-sizeeight': '8px',
    '--font-sizenine': '9px',
    '--font-sizeten': '10px',

    '--font-sizeeleven': '11px',
    '--font-sizetwel': '12px',
    '--font-sizethirteen': '13px',
    '--font-sizefourteen': '14px',
    '--font-sizefifteen': '15px',
    '--font-sizesixteen': '16px',
    '--font-sizeseventeen': '17px',
    '--font-sizeeighteen': '18px',
    '--font-sizenineteen': '19px',
    '--font-sizetwnty': '20px',

    '--font-sizetwntyone': '21px',
    '--font-sizetwntytwo': '22px',
    '--font-sizetwntythree': '23px',
    '--font-sizetwntyfoure': '24px',
    '--font-sizetwntyfive': '25px',
    '--font-sizetwntysix': '26px',
    '--font-sizetwntyseven': '27px',
    '--font-sizetwntyeight': '28px',
    '--font-sizetwntynine': '29px',

    '--font-sizethirty': '30px',
    '--font-sizethirtyone': '31px',
    '--font-sizethirtytwo': '32px',
    '--font-sizethirtythree': '33px',
    '--font-sizethirtyfor': '34px',
    '--font-sizethirtyfive': '35px',
    '--font-sizethirtysix': '36px',
    '--font-sizethirtyseven': '37px',
    '--font-sizethirtyeight': '38px',
    '--font-sizethirtynine': '39px',

    '--font-sizefourty': '40px',
    '--font-sizefourtyone': '41px',
    '--font-sizefourtytwo': '42px',
    '--font-sizefourtythree': '43px',
    '--font-sizefourtyfour': '44px',
    '--font-sizefourtyfive': '45px',
    '--font-sizefourtysix': '46px',
    '--font-sizefourtyseven': '47px',
    '--font-sizefourtyeight': '48px',
    '--font-sizefourtynine': '49px',

    '--font-sizefifty': '50px',
    '--font-sizefiftyone': '51px',
    '--font-sizefiftytwo': '52px',
    '--font-sizefiftythree': '53px',
    '--font-sizefiftyfour': '54px',
    '--font-sizefiftyfive': '55px',
    '--font-sizefiftysix': '56px',
    '--font-sizefiftyseven': '57px',
    '--font-sizefiftyeight': '58px',
    '--font-sizefiftynine': '59px',

    '--font-sizesixty': '60px',
    '--font-sizesixtyone': '61px',
    '--font-sizesixtytwo': '62px',
    '--font-sizesixtythree': '63px',
    '--font-sizesixtyfour': '64px',
    '--font-sizesixtyfive': '65px',
    '--font-sizesixtysix': '66px',
    '--font-sizesixtyseven': '67px',
    '--font-sizesixtyeight': '68px',
    '--font-sizesixtynine': '69px',
    '--font-sizeseventy': '70px',
  }
};

