import { Theme } from './symbols';

export const smallFonts: Theme = {
  name: 'small',
  properties: {
    '--font-sizefive': '2px',
    '--font-sizesix': '3px',
    '--font-sizeseven': '4px',
    '--font-sizeeight': '5px',
    '--font-sizenine': '6px',
    '--font-sizeten': '7px',

    '--font-sizeeleven': '8px',
    '--font-sizetwel': '9px',
    '--font-sizethirteen': '10px',
    '--font-sizefourteen': '11px',
    '--font-sizefifteen': '12px',
    '--font-sizesixteen': '13px',
    '--font-sizeseventeen': '14px',
    '--font-sizeeighteen': '15px',
    '--font-sizenineteen': '16px',
    '--font-sizetwnty': '17px',

    '--font-sizetwntyone': '18px',
    '--font-sizetwntytwo': '19px',
    '--font-sizetwntythree': '20px',
    '--font-sizetwntyfoure': '21px',
    '--font-sizetwntyfive': '22px',
    '--font-sizetwntysix': '23px',
    '--font-sizetwntyseven': '24px',
    '--font-sizetwntyeight': '25px',
    '--font-sizetwntynine': '26px',

    '--font-sizethirty': '27px',
    '--font-sizethirtyone': '28px',
    '--font-sizethirtytwo': '29px',
    '--font-sizethirtythree': '30px',
    '--font-sizethirtyfor': '31px',
    '--font-sizethirtyfive': '32px',
    '--font-sizethirtysix': '33px',
    '--font-sizethirtyseven': '34px',
    '--font-sizethirtyeight': '35px',
    '--font-sizethirtynine': '36px',

    '--font-sizefourty': '37px',
    '--font-sizefourtyone': '38px',
    '--font-sizefourtytwo': '39px',
    '--font-sizefourtythree': '40px',
    '--font-sizefourtyfour': '41px',
    '--font-sizefourtyfive': '42px',
    '--font-sizefourtysix': '43px',
    '--font-sizefourtyseven': '44px',
    '--font-sizefourtyeight': '45px',
    '--font-sizefourtynine': '46px',

    '--font-sizefifty': '47px',
    '--font-sizefiftyone': '48px',
    '--font-sizefiftytwo': '49px',
    '--font-sizefiftythree': '50px',
    '--font-sizefiftyfour': '51px',
    '--font-sizefiftyfive': '52px',
    '--font-sizefiftysix': '53px',
    '--font-sizefiftyseven': '54px',
    '--font-sizefiftyeight': '55px',
    '--font-sizefiftynine': '56px',

    '--font-sizesixty': '57px',
    '--font-sizesixtyone': '58px',
    '--font-sizesixtytwo': '59px',
    '--font-sizesixtythree': '60px',
    '--font-sizesixtyfour': '61px',
    '--font-sizesixtyfive': '62px',
    '--font-sizesixtysix': '63px',
    '--font-sizesixtyseven': '64px',
    '--font-sizesixtyeight': '65px',
    '--font-sizesixtynine': '66px',
    '--font-sizeseventy': '67px',
  }
};

