import { Theme } from './symbols';

export const largeFonts: Theme = {
  name: 'large',
  properties: {
    '--font-sizefive': '8px',
    '--font-sizesix': '9px',
    '--font-sizeseven': '10px',
    '--font-sizeeight': '11px',
    '--font-sizenine': '12px',
    '--font-sizeten': '13px',

    '--font-sizeeleven': '14px',
    '--font-sizetwel': '15px',
    '--font-sizethirteen': '16px',
    '--font-sizefourteen': '17px',
    '--font-sizefifteen': '18px',
    '--font-sizesixteen': '19px',
    '--font-sizeseventeen': '20px',
    '--font-sizeeighteen': '21px',
    '--font-sizenineteen': '22x',
    '--font-sizetwnty': '23px',

    '--font-sizetwntyone': '24px',
    '--font-sizetwntytwo': '25px',
    '--font-sizetwntythree': '26px',
    '--font-sizetwntyfoure': '27px',
    '--font-sizetwntyfive': '28px',
    '--font-sizetwntysix': '29px',
    '--font-sizetwntyseven': '30px',
    '--font-sizetwntyeight': '31px',
    '--font-sizetwntynine': '32px',

    '--font-sizethirty': '33px',
    '--font-sizethirtyone': '34px',
    '--font-sizethirtytwo': '35px',
    '--font-sizethirtythree': '36px',
    '--font-sizethirtyfor': '37px',
    '--font-sizethirtyfive': '38px',
    '--font-sizethirtysix': '39px',
    '--font-sizethirtyseven': '40px',
    '--font-sizethirtyeight': '41px',
    '--font-sizethirtynine': '42px',

    '--font-sizefourty': '43px',
    '--font-sizefourtyone': '44px',
    '--font-sizefourtytwo': '45px',
    '--font-sizefourtythree': '46px',
    '--font-sizefourtyfour': '47px',
    '--font-sizefourtyfive': '48px',
    '--font-sizefourtysix': '49px',
    '--font-sizefourtyseven': '50px',
    '--font-sizefourtyeight': '51px',
    '--font-sizefourtynine': '52px',

    '--font-sizefifty': '53px',
    '--font-sizefiftyone': '54px',
    '--font-sizefiftytwo': '55px',
    '--font-sizefiftythree': '56px',
    '--font-sizefiftyfour': '57px',
    '--font-sizefiftyfive': '58px',
    '--font-sizefiftysix': '59px',
    '--font-sizefiftyseven': '60px',
    '--font-sizefiftyeight': '61px',
    '--font-sizefiftynine': '62px',

    '--font-sizesixty': '63px',
    '--font-sizesixtyone': '64px',
    '--font-sizesixtytwo': '65px',
    '--font-sizesixtythree': '66px',
    '--font-sizesixtyfour': '67px',
    '--font-sizesixtyfive': '68px',
    '--font-sizesixtysix': '69px',
    '--font-sizesixtyseven': '70px',
    '--font-sizesixtyeight': '71px',
    '--font-sizesixtynine': '72px',
    '--font-sizeseventy': '73px',
  }
};

